version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: health_db
    restart: always
    environment:
      POSTGRES_USER: group_user
      POSTGRES_PASSWORD: group_pass
      POSTGRES_DB: health_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cleaned_data:/data

volumes:
  pgdata: