version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: health_db
    restart: always
    environment:
      POSTGRES_USER: group_user
      POSTGRES_PASSWORD: group_pass
      POSTGRES_DB: health_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./cleaned_data:/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zuyd.nl
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pgdata: